---
# vi: ft=ansible
# tasks file for shiny-octo-garbanzo/
  - debug: var=external_ip
    tags:
      - ip

  - name: check vagrant user
    user:
      name: '{{ user }}'
    register: vagrant
    tags:
      - sonarr
      - trans

  - name: apt-get docker stuff
    apt:
      name: '{{ item }}'
      state: present
      cache_valid_time: 36000
      update_cache: yes
    with_items:
      - python-pip
      - unzip
    tags:
      - apt

  - name: install pip stuff
    pip:
      name: '{{ item }}'
      state: present
    with_items:
      - docker-py==1.9.0

  - include: transmission.yml
    tags:
      - trans

  - name: create directories
    file:
      path: '{{ item }}'
      state: directory
      owner: '{{ user }}'
      group: '{{ user }}'
    with_items:
      - '/home/{{ user }}/sonarr'
    tags:
      - mkdir

  - block:
    - name: find out backups to restore
      shell: find sonarr/backups/manual -type f -name '*zip' | sort | tail -1
      register: backups

    - name: validate backup file presence
      stat:
        path: '{{ backups.stdout }}'
      register: backup

    - debug: var=backup.stat.path
    delegate_to: localhost
    become: false
    tags:
      - restore

  - name: extract backup to the config location
    unarchive:
      src: '{{ backups.stdout }}'
      dest: '/home/{{ user }}/sonarr'
      owner: '{{ user }}'
      group: '{{ user }}'
    when: backup.stat.exists
    tags:
      - restore

  - name: create sonarr container
    docker_container:
      name: sonarr
      restart_policy: always
      restart: '{{ restart }}'
      image: linuxserver/sonarr
      links:
        - transmission
      env:
        PGID: '{{ vagrant.group }}'
        PUID: '{{ vagrant.uid }}'
      ports:
        - '8989:8989'
      volumes:
        - '/dev/rtc:/dev/rtc:ro'
        - '{{ downloads }}:/downloads'
        - '/home/{{ user }}/sonarr:/config'
    tags:
      - sonarr

  - include: pia.yml
    tags:
      - pia

  - include: squid.yml
    when: squid

  - name: Post installation tests
    include: tests.yml
    tags:
      - test
