---
# vi: ft=ansible

  - name: create transmissiondirectories
    file:
      path: '{{ item }}'
      state: directory
    with_items:
      - /etc/transmission/
  - name: deploy transmission config
    template:
      src: settings.json
      dest: /etc/transmission/settings.json

  - name: create docker container
    docker_container:
      name: transmission
      restart_policy: always
      restart: '{{ restart }}'
      image: linuxserver/transmission
      volumes:
        - '/etc/transmission:/config'
        - '/downloads:/downloads'
      env:
        PGID: '{{ vagrant.group }}'
        PUID: '{{ vagrant.uid }}'
        TZ: Europe/London
      ports:
        - '9091:9091'
        - '51413:51413'
        - '51413:51413/udp'
